### ISSUE TITLE
Using babel for ES6

### ISSUE THREAD

**Issue by karlbright** [fendersperth/fendersbot#11]
We've broken ground on the code base and i'm keen to see us get some of the lower level details knocked out now. I think we can all agree that if we're going to do a project to mess with and learn from, then we should probably be using ECMAscript6, in the way of Babel.

The biggest issue we have is what stage/preset we want to use. We could look at allowing experimental features, but there could be a stability cost here, albeit quite low.

Thoughts?

**Comment by luke-john** [comment]
+1 for stage 0.

**Comment by kevincharm** [comment]
We should definitely be using ES2015 at the least. Do you guys use stage 0 features in React? (I've not looked into it)

**Comment by luke-john** [comment]
So it looks like the only feature I'm using that I thought was stage 0 moved to stage 1 a while ago.

So I'm happy with stage-1.

**Comment by luke-john** [comment]
For development I currently use nodemon to run babel-node on `/src`.

Then for production `npm postinstall` compiles `/src` to `/dist` which is then run by `npm start`.

And for tests I run babel through mochas `--compilers` option.

I've also taken to placing babels config in the package.json.

Would be interested to hear how others are using it.
