### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by luke-john** [fendersperth/fendersbot#13]
Does anyone have opinions/suggestions about what testing framework and interface is used?

I'm most familiar with mocha and bdd style, but happy with anything.

**Comment by karlbright** [comment]
I feel like Mocha + BDD is the way to go for this. I use [Tape](http://npmjs.org/package/tape) a lot as well, but I feel like Mocha syntax will make it easier for people to understand and learn from, and write.

I'm :+1: for Mocha with something like `Chai` or `expect`for assertions.
