### ISSUE TITLE
Add merge guidelines to README.md

### ISSUE THREAD

**Issue by luke-john** [fendersperth/fendersbot#19]
From discussion on Fenders chat people are happy with the following rules.

Once a pull request receives  +1 from a core contributor it is ready to be merged.

Core contributors should generally be responsible for merging their own pull requests once they have received a +1.

https://fenders.slack.com/?redir=%2Farchives%2Ffenders%2Fp1449022803000658

**Comment by kevincharm** [comment]
Should we define the core contributors also?

**Comment by luke-john** [comment]
That can probably be changed to members of the fenders organisation.

Though currently only 4 of the organisation's members have set their membership to public.

**Comment by pzi** [comment]
I was about to say the same about defining core contributors. Could be determined based on most commits or some metric from Graphs: https://github.com/fendersperth/fendersbot/graphs/contributors
