### ISSUE TITLE
Building blocks and breaking ground

### ISSUE THREAD

**Issue by karlbright** [fendersperth/fendersbot#2]
This project is currently empty and wanted to get an idea on what people would like to see for laying the ground work on this project. Is there a framework / library or language that people are particularly interested in learning/using here?

I'd be keen to go into something like Node on backend with React on the frontend as I feel this fits what most people would be looking to ideally use in their day to day jobs, but we should discuss this and discuss starting blocks for this. Start small etc.

**Comment by Tombre** [comment]
I'd like to see how the pro's setup a real-world react application :+1:

**Comment by phuongy** [comment]
Happy to go with node and react + redux.

**Comment by kevincharm** [comment]
Express to serve the API then?

**Comment by karlbright** [comment]
This all sounds pretty good.

React + Redux front end with server side rendering and API from express?

**Comment by pzi** [comment]
Could go all out with http://swagger.io/ for API :)

**Comment by karlbright** [comment]
Closing this for the time being. Some of the other tasks and scaffolding we need should be detailed in separate issues.
