### ISSUE TITLE
Botkit

### ISSUE THREAD

**Issue by karlbright** [fendersperth/fendersbot#22]
https://github.com/howdyai/botkit was mentioned in Node Weekly this week, it looks pretty solid. Thoughts?

**Comment by luke-john** [comment]
:+1: looks great!

**Comment by kevincharm** [comment]
Just skimmed through it, does it offer much more than the slack-client package? It's probably easier for beginners to pick up and hack with but then you don't really get to learn how the bot is interacting with Slack?

**Comment by luke-john** [comment]
It has documentation which is a huge one up on slack-client.

**Comment by kevincharm** [comment]
I don't mind if you guys want to switch to using this. I have some free time from now til new year to work on stuff!

**Comment by karlbright** [comment]
See #23
