### ISSUE TITLE
Testing slack integrations

### ISSUE THREAD

**Issue by karlbright** [fendersperth/fendersbot#27]
We need some basic functionality around testing slack integrations such as responses, slash commands etc. We shouldn't need to rely on starting a bot and checking each command manually.

Some quick ideas in my mind here and very high level process on how this might go for:
- Mock user
- Mock message
- Trigger callbacks on our bot with given message and user with given callback
- Callback gets return value of our slash command or response callback function
- Spy on bot fns
- Ensure that we're getting what we expect.

Because Botkit handled sending our messages etc to Slack, we don't need to test that. All we care about is testing that we get the expected response from our callback functions, check that `bot.replyPublic` was called with the correct value etc.

**Comment by luke-john** [comment]
We can probably test the callbacks without the bot.

All the other parts are framework features and _should_ be covered by Botkits tests

**Comment by karlbright** [comment]
I think we should still be testing that the bot methods we expect to be called are called with the correct arguments. But this of course can be stubbed.

**Comment by luke-john** [comment]
Sure, that makes sense.

Did you want to add tests as part of #23, or merge and convert to es6 first?

**Comment by karlbright** [comment]
I've added tests to #29 which gives us a good starting point.

**Comment by karlbright** [comment]
Closing as this has been used for #29 and merged. We will need to do some more work on this for slash commands and i've already got some ideas on how to handle things like Meetup and LastFM integrations with ease.
