### ISSUE TITLE
Running in production

### ISSUE THREAD

**Issue by karlbright** [fendersperth/fendersbot#30]
The bot is now running in production! :confetti_ball: 

But there are some "issues" around this. Currently we're running it via Heroku on a sleepless tier, this means that it's cost $7 a month. I have a few DigitalOcean droplets and feel it's probably better off running it on on of those rather than having an additional cost involved in keeping this running.

Also, this is currently a manual process via pushing to heroku, and I think it would be cool to see it deployed on "green" master changes and. We just need to ensure that we have tests on anything that gets merged into master.

Thoughts? Ideas? Anyone want to take control of this?

**Comment by kevincharm** [comment]
I don't mind doing devops stuff if you don't want to do it. I'm sure we can get some members to contribute some $$$ to use your droplets/spin up a dedicated though!

**Comment by karlbright** [comment]
I'm just putting this out there in case anyone was keen to look in to it. I don't mind taking this if no one is interested, but just keep us updating if you start on this. Again, I don't mind doing the heroku for the time being so maybe we should split this out to 2 tasks.
1. Deploy on passing tests on master (easy with Heroku via Travis)
2. Move to droplet to save cost (optional and not required immediately)

**Comment by luke-john** [comment]
I reached out to one of the local aws people and they've approved a $500 credit for fenders if we want to move this there.

**Comment by kevincharm** [comment]
Moving to AWS would be awesome :)
