### ISSUE TITLE
Auto update #fenders channel topic 

### ISSUE THREAD

**Issue by luke-john** [fendersperth/fendersbot#4]
Would be useful to have the channel details for #fenders automatically updated from meetup.com.

**Comment by karlbright** [comment]
Are you suggesting this go in the topic/subject of the channel or should it be accessible via a command? `!meetup` or something?

**Comment by luke-john** [comment]
I'm suggesting it go in the topic.

 Currently (@ 20151130) the topic contains details for a past meetup.

Fenderbot seems like a good candidate to take on the task of keeping it up to date.

**Comment by karlbright** [comment]
:+1:

**Comment by kevincharm** [comment]
It looks like the Meetup API doesn't feature webhooks. But we can just poll it periodically to get the latest events.
- [Meetup API => /2/events](http://www.meetup.com/meetup_api/docs/2/events/)
- [Slack API => channels.setTopic](https://api.slack.com/methods/channels.setTopic)

**Comment by sephorra** [comment]
+1 on this!! This would be really useful for me.

**Comment by luke-john** [comment]
closing this issue as stale, while cleaning up my old github issues
