### ISSUE TITLE
Be able to ask questions

### ISSUE THREAD

**Issue by cyphix333** [fendersperth/fendersbot#6]
You should be able to ask questions, even stupid ones :)

**Comment by karlbright** [comment]
I don't understand how this is an idea at all? There is the possibility of it answering questions, but how would this work? What do you envision it doing and what is the use for this? You'll need to provide some more information on this rather than a quick comment like this.

**Comment by cyphix333** [comment]
Haha... it was just a passing idea. It came up because I wanted to be able to ask when the next fenders meeting was for example. It should be able to answer common questions like that. :)

**Comment by karlbright** [comment]
The bot will have meetup integration via work from @hellstad so this can be closed.
